### ISSUE TITLE
Flarum 1.0 compatibility 

### ISSUE THREAD

**Issue by Eumobong** [flarumtr/flarum-ext-post-bookmarks#1]
This is a must extension for any flarum community and all credit to the author. Can it be updated to flarum 1.0?

**Comment by clarkwinkelmann** [comment]
I was supposed to publish the original source code of this extension on my namespace some time ago but then kind of forgot. There is now a Flarum 1.0 compatible version at https://github.com/clarkwinkelmann/flarum-ext-post-bookmarks

I'm not sure if you want to keep the version under the flarumtr namespace updated or abandon it in favor of the other namespace.

**Comment by Eumobong** [comment]
OK thanks so much.
